### ISSUE TITLE
Rename the project to `js-sh`?

### ISSUE THREAD

**Issue by KevinWang15** [KevinWang15/js-shell#1]
This project was started as a way to automate ssh routines.
However, I think its scope can be bigger, making it an `sh-in-js` framework, and automating ssh routines is just one of its infinite possibilities.

**Comment by qzyse2017** [comment]
Good idea, but there seems to be some similar works currently, see

https://github.com/kanton-aargau/windows-powershell

https://github.com/rannn505/node-powershell

**Comment by qzyse2017** [comment]
I think `ssh routine` is good enough, and you can focus on error handling for these operations.
